import { describe, expect, it, vi } from 'vitest';
import * as domain from '../index';
import type { LatticeState, Seed128 } from '../index';

type Metrics={basalRadiusCells:number;basalDiameterCells:number;iceCellCount:number;perimeterEdges:number;compactness:number;tipDensity:number;aspectRatio:number|null;armLength:readonly number[];armMass:readonly number[];armLengthCv:number|null;armMassCv:number|null};
type MetricsFn=(state:LatticeState,thicknessCells?:number)=>Metrics;
const candidate=(domain as Record<string,unknown>)['morphologyMetrics'] as MetricsFn|undefined;
const eps=(a:number,b:number)=>expect(Math.abs(a-b)).toBeLessThanOrEqual(32*Number.EPSILON*Math.max(1,Math.abs(b)));
const bit=(n:number)=>{const d=new DataView(new ArrayBuffer(8));d.setFloat64(0,n);return d.getBigUint64(0);};
const bits=(xs:ArrayLike<number>)=>Array.from(xs,bit);
const coords=(R:number)=>{const a:Array<readonly[number,number]>=[];for(let r=-R;r<=R;r++)for(let q=Math.max(-R,-r-R);q<=Math.min(R,-r+R);q++)a.push([q,r]);return a;};
const at=(R:number,q:number,r:number)=>coords(R).findIndex(([x,y])=>x===q&&y===r);
const base=(radius:number):LatticeState=>{const n=1+3*radius*(radius+1);return{radius,waterMass:new Float64Array(n),ice:new Uint8Array(n),noise:new Float64Array(n),stepIndex:0,elapsedCa:0,stopped:false,beta:0,noiseAmplitude:0,seed:[1,2,3,4],modelVersion:'reiter-alpha1-xoshiro128ss-1.1-v1'};};
const clone=(s:LatticeState):LatticeState=>({...s,waterMass:new Float64Array(s.waterMass),ice:new Uint8Array(s.ice),noise:new Float64Array(s.noise),seed:[...s.seed] as Seed128});
const ice=(s:LatticeState,q:number,r:number,mass=0)=>{const i=at(s.radius,q,r);s.ice[i]=1;s.waterMass[i]=mass;return s;};
const fn=()=>{expect(candidate,'morphologyMetrics must be publicly exported').toBeTypeOf('function');return candidate!;};
const omitted=(s:LatticeState)=>fn()(s);
const explicit=(s:LatticeState,t:number|undefined)=>fn()(s,t);
const arr=(a:readonly number[],b:readonly number[])=>{expect(a).toHaveLength(6);a.forEach((x,i)=>eps(x,b[i]!));};
const all=(m:Metrics,e:Metrics)=>{eps(m.basalRadiusCells,e.basalRadiusCells);eps(m.basalDiameterCells,e.basalDiameterCells);expect(m.iceCellCount).toBe(e.iceCellCount);expect(m.perimeterEdges).toBe(e.perimeterEdges);eps(m.compactness,e.compactness);eps(m.tipDensity,e.tipDensity);expect(m.aspectRatio).toBe(e.aspectRatio);arr(m.armLength,e.armLength);arr(m.armMass,e.armMass);e.armLengthCv===null?expect(m.armLengthCv).toBeNull():eps(m.armLengthCv!,e.armLengthCv);e.armMassCv===null?expect(m.armMassCv).toBeNull():eps(m.armMassCv!,e.armMassCv);};
const same=(a:Metrics,b:Metrics)=>{for(const k of ['basalRadiusCells','basalDiameterCells','iceCellCount','perimeterEdges','compactness','tipDensity']as const)expect(bit(a[k])).toBe(bit(b[k]));expect(a.aspectRatio===null?null:bit(a.aspectRatio)).toBe(b.aspectRatio===null?null:bit(b.aspectRatio));expect(bits(a.armLength)).toEqual(bits(b.armLength));expect(bits(a.armMass)).toEqual(bits(b.armMass));expect(a.armLengthCv===null?null:bit(a.armLengthCv)).toBe(b.armLengthCv===null?null:bit(b.armLengthCv));expect(a.armMassCv===null?null:bit(a.armMassCv)).toBe(b.armMassCv===null?null:bit(b.armMassCv));};
const A=()=>{const s=ice(base(3),0,0,7);([[1,1,1],[-1,2,2],[-2,1,3],[-1,-1,4],[1,-2,5],[2,-1,6]]as const).forEach(([q,r,m])=>ice(s,q,r,m));return s;};
const scalar=(x:unknown)=>typeof x==='number'?['number',bit(x)]:[typeof x,x];
const content=(x:unknown)=>{if(ArrayBuffer.isView(x)){const v=x as any;return{kind:'view',tag:Object.prototype.toString.call(x),bytes:Array.from(new Uint8Array(v.buffer,v.byteOffset,v.byteLength))};}if(Array.isArray(x))return{kind:'array',entries:Array.from({length:x.length},(_,i)=>i in x?scalar(x[i]):['hole'])};return{kind:typeof x,value:x};};
const own=(x:object)=>Object.getOwnPropertyNames(x).sort().map(k=>{const d=Object.getOwnPropertyDescriptor(x,k)!;return{key:k,enumerable:d.enumerable,configurable:d.configurable,writable:'writable'in d?d.writable:undefined,get:d.get,set:d.set,value:'value'in d?d.value:undefined};});
const field=(x:object,k:string)=>{const d=Object.getOwnPropertyDescriptor(x,k);return d&&'value'in d?d.value:undefined;};
const snap=(s:unknown)=>{if(s===null||typeof s!=='object')return{primitive:s};const x=s as object;const names=['waterMass','ice','noise','seed']as const;const fields=names.map(k=>{const value=field(x,k);return{key:k,value,content:content(value)};});return{x,properties:own(x),fields};};
const unchanged=(s:unknown,before=snap(s))=>{if('primitive'in before){expect(Object.is(s,before.primitive)).toBe(true);return;}expect(s).toBe(before.x);expect(own(before.x)).toEqual(before.properties);before.fields.forEach(({key,value,content:was})=>{const now=field(before.x,key);expect(now).toBe(value);expect(content(now)).toEqual(was);});};
const reported=(e:unknown)=>String(e).match(/(?:waterMass|ice|noise|seed)\[\d+\]|\b(?:state|radius|waterMass|ice|noise|stepIndex|elapsedCa|stopped|beta|noiseAmplitude|modelVersion|seed|thicknessCells)\b/)?.[0];
const reject=(want:string,s:unknown,t:unknown,kind:typeof TypeError|typeof RangeError)=>{const b=snap(s);if(!candidate){fn();return;}let caught:unknown;try{candidate(s as LatticeState,t as number);}catch(e){caught=e;}expect(caught).toBeInstanceOf(kind);expect(reported(caught)).toBe(want);unchanged(s,b);};
const accept=(s:LatticeState,t?:number)=>{const b=snap(s);expect(()=>t===undefined?omitted(s):explicit(s,t)).not.toThrow();unchanged(s,b);};
const predicates=(q:number,r:number)=>[q>=0&&r>=0,q<0&&r>0&&q+r>=0,q<0&&r>=0&&q+r<0,q<=0&&r<0,q>0&&r<0&&q+r<=0,q>0&&r<0&&q+r>0];

describe('TC-MORPH-000 through 009',()=>{
 it('asserts all literal R=2/R=3 indices',()=>{
  const r2:Array<readonly[number,number,number]>=[[0,0,-2],[1,1,-2],[2,2,-2],[3,-1,-1],[4,0,-1],[5,1,-1],[6,2,-1],[7,-2,0],[8,-1,0],[9,0,0],[10,1,0],[11,2,0],[12,-2,1],[13,-1,1],[14,0,1],[15,1,1],[16,-2,2],[17,-1,2],[18,0,2]];
  const r3:Array<readonly[number,number,number]>=[[0,0,-3],[1,1,-3],[2,2,-3],[3,3,-3],[4,-1,-2],[5,0,-2],[6,1,-2],[7,2,-2],[8,3,-2],[9,-2,-1],[10,-1,-1],[11,0,-1],[12,1,-1],[13,2,-1],[14,3,-1],[15,-3,0],[16,-2,0],[17,-1,0],[18,0,0],[19,1,0],[20,2,0],[21,3,0],[22,-3,1],[23,-2,1],[24,-1,1],[25,0,1],[26,1,1],[27,2,1],[28,-3,2],[29,-2,2],[30,-1,2],[31,0,2],[32,1,2],[33,-3,3],[34,-2,3],[35,-1,3],[36,0,3]];
  r2.forEach(([i,q,r])=>expect(at(2,q,r)).toBe(i));r3.forEach(([i,q,r])=>expect(at(3,q,r)).toBe(i));
 });
 it('000 invokes omitted and explicit undefined independently with +0 outputs',()=>{
  const e={basalRadiusCells:0,basalDiameterCells:0,iceCellCount:0,perimeterEdges:0,compactness:0,tipDensity:0,aspectRatio:null,armLength:[0,0,0,0,0,0],armMass:[0,0,0,0,0,0],armLengthCv:null,armMassCv:null};for(const m of [omitted(base(2)),explicit(base(2),undefined),explicit(base(2),4)]){all(m,e);for(const x of [m.basalRadiusCells,m.basalDiameterCells,m.compactness,m.tipDensity,...m.armLength,...m.armMass])expect(Object.is(x,+0)).toBe(true);}
 });
 it('001/002 center seed and complete hexagon include +0 and every output',()=>{
  const one={basalRadiusCells:0,basalDiameterCells:0,iceCellCount:1,perimeterEdges:6,compactness:6/(Math.PI*Math.sqrt(3)),tipDensity:0,aspectRatio:null,armLength:[0,0,0,0,0,0],armMass:[0,0,0,0,0,0],armLengthCv:null,armMassCv:null};for(const m of [omitted(ice(base(2),0,0,1)),explicit(ice(base(2),0,0,1),undefined),explicit(ice(base(2),0,0,1),0),explicit(ice(base(2),0,0,1),4)]){all(m,one);for(const x of [m.basalRadiusCells,m.basalDiameterCells,m.tipDensity,...m.armLength,...m.armMass])expect(Object.is(x,+0)).toBe(true);}
  const h=ice(base(2),0,0,1);([[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]]as const).forEach(([q,r])=>ice(h,q,r));for(const[t,aspectRatio]of[[undefined,null],[0,0],[4,2]]as const){const m=explicit(clone(h),t);all(m,{basalRadiusCells:1,basalDiameterCells:2,iceCellCount:7,perimeterEdges:18,compactness:54/(7*Math.PI*Math.sqrt(3)),tipDensity:0,aspectRatio,armLength:[1,1,1,1,1,0],armMass:[0,0,0,0,0,0],armLengthCv:1/Math.sqrt(5),armMassCv:null});if(aspectRatio===0)expect(Object.is(m.aspectRatio,+0)).toBe(true);}
 });
 it('003A/B/C/D assert every scalar, array, CV, nullable and 2/3',()=>{
  const ma=omitted(A());all(ma,{basalRadiusCells:Math.sqrt(3),basalDiameterCells:2*Math.sqrt(3),iceCellCount:7,perimeterEdges:42,compactness:42/(Math.PI*Math.sqrt(3)),tipDensity:0,aspectRatio:null,armLength:Array(6).fill(Math.sqrt(3)),armMass:[1,2,3,4,5,6],armLengthCv:0,armMassCv:Math.sqrt(5/21)});expect(Object.is(ma.armLengthCv,+0)).toBe(true);
  const b=ice(base(3),0,0,7);([[1,0,1],[0,1,2],[-1,1,3],[-1,0,4],[0,-1,5],[1,-1,6]]as const).forEach(([q,r,m])=>ice(b,q,r,m));all(omitted(b),{basalRadiusCells:1,basalDiameterCells:2,iceCellCount:7,perimeterEdges:18,compactness:54/(7*Math.PI*Math.sqrt(3)),tipDensity:0,aspectRatio:null,armLength:[1,1,1,1,1,0],armMass:[3,3,4,5,6,0],armLengthCv:1/Math.sqrt(5),armMassCv:Math.sqrt(43/3)/7});
  const c=ice(ice(base(3),0,0,7),1,0,1);all(omitted(c),{basalRadiusCells:1,basalDiameterCells:2,iceCellCount:2,perimeterEdges:10,compactness:25/(3*Math.PI*Math.sqrt(3)),tipDensity:1,aspectRatio:null,armLength:[1,0,0,0,0,0],armMass:[1,0,0,0,0,0],armLengthCv:Math.sqrt(5),armMassCv:Math.sqrt(5)});
  const d=ice(ice(ice(base(3),0,0,7),1,0,1),2,0,1);all(omitted(d),{basalRadiusCells:2,basalDiameterCells:4,iceCellCount:3,perimeterEdges:14,compactness:98/(9*Math.PI*Math.sqrt(3)),tipDensity:2/3,aspectRatio:null,armLength:[2,0,0,0,0,0],armMass:[2,0,0,0,0,0],armLengthCv:Math.sqrt(5),armMassCv:Math.sqrt(5)});
 });
 it('004/005 checks all 36 sector predicates and aspect endpoints',()=>{
  const e:Array<readonly[number,number,number]>=[[0,-3,3],[1,-3,4],[2,-3,4],[3,-3,4],[-1,-2,3],[0,-2,3],[1,-2,4],[2,-2,4],[3,-2,5],[-2,-1,3],[-1,-1,3],[0,-1,3],[1,-1,4],[2,-1,5],[3,-1,5],[-3,0,2],[-2,0,2],[-1,0,2],[1,0,0],[2,0,0],[3,0,0],[-3,1,2],[-2,1,2],[-1,1,1],[0,1,0],[1,1,0],[2,1,0],[-3,2,2],[-2,2,1],[-1,2,1],[0,2,0],[1,2,0],[-3,3,1],[-2,3,1],[-1,3,1],[0,3,0]];e.forEach(([q,r,k])=>{const p=predicates(q,r);expect(p.filter(Boolean)).toHaveLength(1);expect(p.findIndex(Boolean)).toBe(k);});
  const h=ice(base(2),0,0);([[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]]as const).forEach(([q,r])=>ice(h,q,r));for(const[t,want]of[[undefined,null],[-0,0],[+0,0],[Number.MIN_VALUE,0],[4,2],[Number.MAX_VALUE,Number.MAX_VALUE/2]]as const){const m=explicit(clone(h),t);expect(m.aspectRatio).toBe(want);if(want===0)expect(Object.is(m.aspectRatio,+0)).toBe(true);}
 });
 it('006 checks compensation, scaled CV and overflow',()=>{
  const finite=ice(ice(ice(base(3),1,0,2**53),2,0,1),0,1,1);const m=omitted(finite);all(m,{basalRadiusCells:2,basalDiameterCells:4,iceCellCount:3,perimeterEdges:14,compactness:98/(9*Math.PI*Math.sqrt(3)),tipDensity:2/3,aspectRatio:null,armLength:[2,0,0,0,0,0],armMass:[9007199254740994,0,0,0,0,0],armLengthCv:Math.sqrt(5),armMassCv:Math.sqrt(5)});expect(Object.is(m.armMass[0],9007199254740994)).toBe(true);
  const maximum=A();[26,30,23,10,6,13].forEach(i=>{maximum.waterMass[i]=Number.MAX_VALUE;});const mm=omitted(maximum);all(mm,{basalRadiusCells:Math.sqrt(3),basalDiameterCells:2*Math.sqrt(3),iceCellCount:7,perimeterEdges:42,compactness:42/(Math.PI*Math.sqrt(3)),tipDensity:0,aspectRatio:null,armLength:Array(6).fill(Math.sqrt(3)),armMass:Array(6).fill(Number.MAX_VALUE),armLengthCv:0,armMassCv:0});expect(Object.is(mm.armMassCv,+0)).toBe(true);const o=ice(ice(base(3),1,0,Number.MAX_VALUE),0,1,Number.MAX_VALUE);const before=snap(o);expect(()=>omitted(o)).toThrow(RangeError);unchanged(o,before);
 });
 it('007/008 compare all result bits and each irrelevant valid state field',()=>{
  const s=A(),before=snap(s),random=vi.spyOn(Math,'random'),first=omitted(s),second=omitted(s);same(first,second);expect(first).not.toBe(second);expect(first.armLength).not.toBe(second.armLength);expect(first.armMass).not.toBe(second.armMass);(first.armLength as number[])[0]=99;(first.armMass as number[])[0]=99;expect(second.armLength[0]).toBe(Math.sqrt(3));expect(second.armMass[0]).toBe(1);expect(random).not.toHaveBeenCalled();random.mockRestore();unchanged(s,before);
  const ref=omitted(A()),vs:LatticeState[]=[];const vary=(f:(x:any)=>void)=>{const x=A();f(x);vs.push(x);};vary(x=>{x.stepIndex=Number.MAX_SAFE_INTEGER;});vary(x=>{x.elapsedCa=Number.MAX_VALUE;});vary(x=>{x.stopped=true;});vary(x=>{x.beta=.95;});vary(x=>{x.noiseAmplitude=1;});vary(x=>{x.seed=[0,0xffffffff,0,1];});vary(x=>{x.noise.fill(1-Number.EPSILON);});vary(x=>{x.waterMass[0]=Number.MAX_VALUE;});vary(x=>{x.waterMass[18]=Number.MAX_VALUE;});vs.forEach(x=>same(omitted(x),ref));
  const changed=A();changed.waterMass[26]=2;const actual=omitted(changed);for(const k of ['basalRadiusCells','basalDiameterCells','iceCellCount','perimeterEdges','compactness','tipDensity']as const)expect(bit(actual[k])).toBe(bit(ref[k]));expect(actual.aspectRatio).toBe(ref.aspectRatio);expect(bits(actual.armLength)).toEqual(bits(ref.armLength));expect(actual.armLengthCv===null?null:bit(actual.armLengthCv)).toBe(ref.armLengthCv===null?null:bit(ref.armLengthCv));expect(bits(actual.armMass.slice(1))).toEqual(bits(ref.armMass.slice(1)));arr(actual.armMass,[2,2,3,4,5,6]);eps(actual.armMassCv!,2*Math.sqrt(5)/11);
 });
 it('009 counts both sides of a hole',()=>{const s=base(3);([[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]]as const).forEach(([q,r])=>ice(s,q,r));const m=omitted(s);expect(m.iceCellCount).toBe(6);expect(m.perimeterEdges).toBe(24);});
});

describe('TC-MORPH-V01 through V12',()=>{
 it('V01/V02/V03 orders typed arrays waterMass, ice, noise and uses genuine wrong array classes',()=>{
  for(const x of [null,undefined,1,'state',[]])reject('state',x,undefined,TypeError);for(const x of ['2',NaN,Infinity,-Infinity])reject('radius',{...base(2),radius:x as number},undefined,TypeError);for(const x of [1,1.5,2**26,Number.MAX_SAFE_INTEGER])reject('radius',{...base(2),radius:x},undefined,RangeError);
  for(const f of ['waterMass','ice','noise']as const){const wrong=f==='waterMass'?new Uint8Array(19):f==='ice'?new Float64Array(19):new Uint8Array(19);for(const x of [[],null,wrong])reject(f,{...base(2),[f]:x}as LatticeState,undefined,TypeError);for(const n of [18,20])reject(f,{...base(2),[f]:f==='ice'?new Uint8Array(n):new Float64Array(n)}as LatticeState,undefined,RangeError);}const triple={...base(2),waterMass:new Uint8Array(19),ice:new Float64Array(19),noise:new Uint8Array(19)}as unknown as LatticeState;reject('waterMass',triple,undefined,TypeError);const iceFirst={...base(2),ice:new Float64Array(19),noise:new Uint8Array(19)}as unknown as LatticeState;reject('ice',iceFirst,undefined,TypeError);
 });
 it('V04/V05/V06 accepts all listed metadata and seed boundaries, then rejects invalid forms',()=>{
  const fields:Array<readonly[string,unknown[],unknown[]]>=[['stepIndex',['0',NaN,Infinity,-Infinity],[-1,.5,2**53]],['elapsedCa',['0',NaN,Infinity,-Infinity],[-1]],['beta',['0',NaN,Infinity,-Infinity],[-Number.MIN_VALUE,.95+Number.EPSILON]],['noiseAmplitude',['0',NaN,Infinity,-Infinity],[-Number.MIN_VALUE,1+Number.EPSILON]]];for(const[f,types,ranges]of fields){for(const x of types)reject(f,{...base(2),[f]:x}as LatticeState,undefined,TypeError);for(const x of ranges)reject(f,{...base(2),[f]:x}as LatticeState,undefined,RangeError);}
  for(const f of [(x:any)=>{x.stepIndex=Number.MAX_SAFE_INTEGER;},(x:any)=>{x.elapsedCa=-0;},(x:any)=>{x.elapsedCa=Number.MIN_VALUE;},(x:any)=>{x.elapsedCa=Number.MAX_VALUE;},(x:any)=>{x.beta=.95;},(x:any)=>{x.noiseAmplitude=1;},(x:any)=>{x.seed=[0,0xffffffff,0,1];}]){const s=base(2);f(s);accept(s);}
  for(const x of [0,'false',null])reject('stopped',{...base(2),stopped:x}as unknown as LatticeState,undefined,TypeError);reject('modelVersion',{...base(2),modelVersion:'wrong'},undefined,TypeError);for(const x of [null,new Uint32Array(4),[1,2,3],[1,2,3,4,5]])reject('seed',{...base(2),seed:x}as unknown as LatticeState,undefined,TypeError);for(let i=0;i<4;i++){for(const x of ['1',NaN,Infinity,-Infinity]){const s=base(2),z=[...s.seed]as unknown[];z[i]=x;reject(`seed[${i}]`,{...s,seed:z}as unknown as LatticeState,undefined,TypeError);}for(const x of [-1,.5,2**32]){const s=base(2),z=[...s.seed]as unknown[];z[i]=x;reject(`seed[${i}]`,{...s,seed:z}as unknown as LatticeState,undefined,RangeError);}}reject('seed',{...base(2),seed:[0,0,0,0]},undefined,RangeError);reject('seed[1]',{...base(2),seed:[1,-1,'bad',4]as unknown as Seed128},undefined,RangeError);
 });
 it('V07/V08 accepts every listed valid cell boundary and rejects invalid cells',()=>{
  for(const i of [0,9,18]){for(const x of [-Number.MIN_VALUE,NaN,Infinity,-Infinity]){const s=base(2);s.waterMass[i]=x;reject(`waterMass[${i}]`,s,undefined,RangeError);}for(const x of [-1-Number.EPSILON,1,NaN,Infinity,-Infinity]){const s=base(2);s.noise[i]=x;reject(`noise[${i}]`,s,undefined,RangeError);}for(const x of [2,255]){const s=base(2);s.ice[i]=x;reject(`ice[${i}]`,s,undefined,RangeError);}}
  for(const i of [0,9,18])for(const f of [(s:LatticeState)=>{s.waterMass[i]=-0;},(s:LatticeState)=>{s.waterMass[i]=Number.MAX_VALUE;},(s:LatticeState)=>{s.noise[i]=-1;},(s:LatticeState)=>{s.noise[i]=1-Number.EPSILON;}]){const s=base(2);f(s);accept(s);}for(const i of [0,18]){const s=base(2);s.ice[i]=1;reject(`ice[${i}]`,s,undefined,RangeError);}const nonIce=base(2);nonIce.waterMass[0]=1;accept(nonIce);const mismatch=base(2) as any;mismatch.waterMass[0]=Number.MAX_VALUE;mismatch.beta=.95;accept(mismatch);accept(base(2));accept(ice(base(2),1,0));accept(ice(ice(base(2),-1,0),1,0));
 });
 it('V09/V10/V11/V12 preserves every specified precedence and leaves thickness last',()=>{
  for(const x of ['0',null,NaN,Infinity,-Infinity])reject('thicknessCells',base(2),x,TypeError);for(const x of [-Number.MIN_VALUE,-1])reject('thicknessCells',base(2),x,RangeError);for(const x of [undefined,-0,+0,Number.MIN_VALUE,Number.MAX_VALUE])accept(base(2),x);
  const both=base(2);both.waterMass[9]=-1;both.ice[9]=2;both.noise[9]=1;reject('waterMass[9]',both,undefined,RangeError);const iceNoise=base(2);iceNoise.ice[9]=2;iceNoise.noise[9]=1;reject('ice[9]',iceNoise,undefined,RangeError);const ordered=base(2);ordered.noise[0]=1;ordered.waterMass[18]=-1;reject('noise[0]',ordered,undefined,RangeError);
  const pairs:Array<readonly[string,string,unknown,unknown,typeof TypeError|typeof RangeError]>=[['stepIndex','elapsedCa',-1,-1,RangeError],['elapsedCa','stopped',-1,0,RangeError],['stopped','beta',0,-1,TypeError],['beta','noiseAmplitude',-1,-1,RangeError],['noiseAmplitude','modelVersion',-1,'wrong',RangeError],['modelVersion','seed','wrong',[0,0,0,0],TypeError]];for(const[first,second,a,b,kind]of pairs)reject(first,{...base(2),[first]:a,[second]:b}as LatticeState,undefined,kind);
  reject('radius',{...base(2),radius:1,waterMass:[]}as unknown as LatticeState,undefined,RangeError);reject('waterMass',{...base(2),waterMass:[],ice:[]}as unknown as LatticeState,undefined,TypeError);reject('noise',{...base(2),noise:[],stepIndex:-1}as unknown as LatticeState,undefined,TypeError);reject('seed',{...base(2),seed:[0,0,0,0],noise:new Float64Array(19).fill(1)}as LatticeState,undefined,RangeError);reject('radius',{...base(2),radius:1},-1,RangeError);
 });
});
