import { describe, expect, it, vi } from 'vitest';
import * as domain from '../index';
import type { LatticeState } from '../index';

type Parameters = { readonly beta: number; readonly gamma: number; readonly noiseAmplitude: number; readonly dtCa: number };
type Result = { readonly state: LatticeState; readonly ledger: Record<string, number>; readonly reachedEdge: boolean };
const step = (domain as typeof domain & { step?: (state: LatticeState, p: Parameters) => Result }).step;
const bits = (value: number) => { const view = new DataView(new ArrayBuffer(8)); view.setFloat64(0, value); return view.getBigUint64(0); };
const stateBits = (state: LatticeState) => ({ water: Array.from(state.waterMass, bits), ice: Array.from(state.ice), noise: Array.from(state.noise, bits), seed: [...state.seed], fields: [state.radius, state.stepIndex, bits(state.elapsedCa), state.stopped, bits(state.beta), bits(state.noiseAmplitude), state.modelVersion] });
const ledgerFields = ['beforeTotal', 'afterTotal', 'diffusionNet', 'outOfPlaneInput', 'reservoirExchange', 'residual'] as const;
const ledgerBits = (ledger: Record<string, number>) => { for (const field of ledgerFields) { expect(Object.hasOwn(ledger, field)).toBe(true); expect(typeof ledger[field]).toBe('number'); expect(Number.isFinite(ledger[field]!)).toBe(true); } return { beforeTotal: bits(ledger.beforeTotal!), afterTotal: bits(ledger.afterTotal!), diffusionNet: bits(ledger.diffusionNet!), outOfPlaneInput: bits(ledger.outOfPlaneInput!), reservoirExchange: bits(ledger.reservoirExchange!), residual: bits(ledger.residual!) }; };
const resultBits = (result: Result) => ({ state: stateBits(result.state), ledger: ledgerBits(result.ledger), reachedEdge: result.reachedEdge });
const invoke = (s: LatticeState, p: Parameters) => { expect(step).toBeTypeOf('function'); return step!(s, p); };

describe('TC-STEP-013–016: stopped fixed point, purity, and bit replay', () => {
  const controls: readonly Parameters[] = [{ beta: 2 / 5, gamma: 1 / 8, noiseAmplitude: 1 / 4, dtCa: 1 }, { beta: 3 / 5, gamma: 0, noiseAmplitude: 1 / 2, dtCa: 1 / 2 }, { beta: 1 / 5, gamma: 1 / 4, noiseAmplitude: 1 / 4, dtCa: 1 }];
  const run = () => { let state = domain.createLattice({ radius: 3, seed: [1, 2, 3, 4], beta: 2 / 5, noiseAmplitude: 1 / 4 }); const output: Result[] = []; for (const p of controls) { const before = stateBits(state); const out = invoke(state, p); expect(stateBits(state)).toEqual(before); expect(Array.from(out.state.noise, bits)).toEqual(before.noise); expect([...out.state.seed]).toEqual(before.seed); expect(out.state).not.toBe(state); expect(out.state.waterMass).not.toBe(state.waterMass); expect(out.state.ice).not.toBe(state.ice); expect(out.state.noise).not.toBe(state.noise); expect(out.state.seed).not.toBe(state.seed); output.push(out); state = out.state; } return output; };
  it('TC-STEP-015 replays a fixed seed and ordered numerical control sequence bit-for-bit', () => { expect(run().map(resultBits)).toEqual(run().map(resultBits)); });
  it('TC-STEP-016 does not use Math.random or alter an earlier result through later calls', () => { const spy = vi.spyOn(Math, 'random'); const output = run(); expect(spy).not.toHaveBeenCalled(); const first = resultBits(output[0]!); invoke(output[1]!.state, controls[2]!); expect(resultBits(output[0]!)).toEqual(first); spy.mockRestore(); });
  it('TC-STEP-016 keeps each input bit-identical when its returned mutable storage is changed', () => { const input = domain.createLattice({ radius: 3, seed: [1, 2, 3, 4], beta: 2 / 5, noiseAmplitude: 1 / 4 }); const before = stateBits(input); const out = invoke(input, controls[0]!); out.state.waterMass[0] = Number.NaN; expect(stateBits(input)).toEqual(before); out.state.ice[0] = 255; expect(stateBits(input)).toEqual(before); out.state.noise[0] = Number.NaN; expect(stateBits(input)).toEqual(before); (out.state.seed as [number, number, number, number])[0] ^= 1; expect(stateBits(input)).toEqual(before); });
  it('TC-STEP-013 returns a copying, all-zero-flow fixed point after an edge stop', () => { const state = domain.createLattice({ radius: 2, seed: [1, 2, 3, 4], beta: 2 / 5, noiseAmplitude: 0 }); const stopped = invoke(state, { beta: 2 / 5, gamma: 1 / 2, noiseAmplitude: 0, dtCa: 1 }); expect(stopped.state.stopped).toBe(true); expect(stopped.ledger.afterTotal).toBe(123 / 10); const before = stateBits(stopped.state); const out = invoke(stopped.state, { beta: 0, gamma: 1, noiseAmplitude: 1, dtCa: 1 / 2 }); expect(stateBits(out.state)).toEqual(before); expect(out.reachedEdge).toBe(true); const fixed = ledgerBits(out.ledger); expect(out.ledger.beforeTotal).toBe(123 / 10); expect(out.ledger.afterTotal).toBe(123 / 10); expect(fixed.beforeTotal).toBe(bits(123 / 10)); expect(fixed.afterTotal).toBe(bits(123 / 10)); for (const field of ['diffusionNet', 'outOfPlaneInput', 'reservoirExchange', 'residual'] as const) expect(Object.is(out.ledger[field]!, +0)).toBe(true); expect(out.state.waterMass).not.toBe(stopped.state.waterMass); expect(out.state.ice).not.toBe(stopped.state.ice); expect(out.state.noise).not.toBe(stopped.state.noise); expect(out.state.seed).not.toBe(stopped.state.seed); });
});
